services:
  service-a:
    image: alpine:latest
    container_name: bai14_service_a
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    networks:
      - private_net

  service-b:
    image: alpine:latest
    container_name: bai14_service_b
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    networks:
      - private_net

networks:
  private_net:
    driver: bridge
