services:
  redis:
    image: redis:latest
    container_name: bai15_redis_limited
    ports:
      - "6380:6379"
    cpus: 0.50
    mem_limit: 256m
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
